name: Run Cypress Tests on BrowserStack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests on BrowserStack
      uses: browserstack/github-action-cypress@v1
      with:
        browserstack_username: ${{ secrets.BROWSERSTACK_USERNAME }}
        browserstack_access_key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
